os: linux
dist: xenial
language: python
python:
  - 3.6
cache: pip
install: travis_retry pip install tox\>=3.1.2 codecov
script: tox -e $TOX_ENV
jobs:
  fast_finish: true
  include:
    - python: 3.6
      env: TOX_ENV=docs
    - python: 3.6
      env: TOX_ENV=lint
    - python: 3.6
      env: TOX_ENV=no_rest_framework
    - python: 3.7
      env: TOX_ENV=django_master-py37
    - python: 3.6
      env: TOX_ENV=django_master-py36
    - python: 3.7
      env: TOX_ENV=django30-py37
    - python: 3.6
      env: TOX_ENV=django30-py36
    - python: 3.7
      env: TOX_ENV=django22-py37
    - python: 3.6
      env: TOX_ENV=django22-py36
    - python: 3.7
      env: TOX_ENV=django21-py37
    - python: 3.6
      env: TOX_ENV=django21-py36
    - python: 3.6
      env: TOX_ENV=django111-py36
    - python: 3.5
      env: TOX_ENV=django21-py35
    - python: pypy3
      env: TOX_ENV=django21-pypy3
    - python: 3.5
      env: TOX_ENV=django111-py35
    - python: 3.5
      env: TOX_ENV=django22-py35
after_success:
  - codecov
